filter-tree: Use a table layout in filter tree
theia-ide/theia-trace-extension pull request #116
Opened 2020-09-04 20:36 UTC by tahini

This allows to display many columns in the tree. Columns are sortable.

Signed-off-by: Lea <lea.carlier@polymtl.ca>
Signed-off-by: Geneviève Bastien <gbastien+lttng@versatic.net>

2020-09-09 14:05 UTC, chertyb commented on viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table-row.tsx
> +                {children}
we can call this.renderChildren() directly

2020-09-10 13:38 UTC, chertyb commented on viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table.tsx
> +    getTableHeaderKeys = (): string[] => {
add TODO: remove hardcoded values when trace-server can send column headers

2020-09-10 13:54 UTC, chertyb requested changes
table works fine, only add TODO and I'll approve the request

2020-09-11 20:37 UTC, chertyb approved these changes

2020-09-25 01:54 UTC, bhufmann commented
Just to let you know that I've started looking at the patch and review is ongoing.

2020-09-25 14:30 UTC, bhufmann requested changes
Thanks for adding the table. It's a nice addition to the Time Graph and the XY charts. It will be useful when implementing a statistics view.

The columns are quite undefined. They depend on the extra attributes TimeGraphEntryModel implementation of each data provider. We'll need to use the columns headers and labels for each rows, that are currently defined in the TSP, but no time graph nor xy data provider has implemented it yet. Also, the trace server and tsp-typescript-client should ignore attributes that are not in the TSP. This is outside the scope of this PR.

2020-09-25 15:31 UTC, tahini commented
I added the todo, for the table headers and label, since changes are required in the tsp-client and trace server, it can be for later patches?

2020-09-25 18:02 UTC, bhufmann commented
> I added the todo, for the table headers and label, since changes are required in the tsp-client and trace server, it can be for later patches?

I think so. Maybe have the trace server patch [1] that only serializes fields that are in the TSP and related tsp-client patch should be merged first. Then, the time graphs won't unnecessary columns.

[1] https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/167256

2020-09-25 18:03 UTC, bhufmann commented
Another question, the Legend column doesn't really make sense for time graphs, right?

2020-09-29 19:36 UTC, bhufmann commented
> Another question, the Legend column doesn't really make sense for time graphs, right?

After testing, I realized that the Legend column is only for XY charts and not for time graph.

2020-09-29 19:38 UTC, bhufmann approved these changes
It looks good to me

2020-10-02 13:07 UTC, tahini commented
Simply rebased, I'll merge for now so the update with the new tsp patches will be more obvious.

2020-10-02 13:08 UTC, merged

2020-10-02 13:08 UTC, tahini commented
Thanks @chertyb for this great improvement!