Fixed handling of row-click event
theia-ide/theia-trace-extension pull request #150
Opened 2020-10-13 03:07 UTC by muddana-satish

Feature was working with earlier versions of PIXI.
Current PIXI is not able to handle events for the elements with opacity 0.
Changed the Opacity as a workaround fix.

Fixes https://github.com/theia-ide/timeline-chart/issues/52

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

2020-10-13 04:02 UTC, muddana-satish commented
This may not be the right fix. This should be handled by PIXI even for the elements with opacity 0. But as a work around I changed the opacity to 0.01. 

This is how it works after the changes:
![Row select](https://user-images.githubusercontent.com/70230232/95813968-057ff400-0cce-11eb-957c-7eba2ce44b63.gif)





Visually the chart looks the same.Attaching the screenshots for comparison.

**Current Version:**
(without selecting row)
![image](https://user-images.githubusercontent.com/70230232/95811004-2c86f780-0cc7-11eb-9c2d-dcaf8841f3f8.png)
(selecting row)
![image](https://user-images.githubusercontent.com/70230232/95811047-47f20280-0cc7-11eb-8416-d919cb01f298.png)

**After changing Opacity to 0.01:**
(without selecting row)
![image](https://user-images.githubusercontent.com/70230232/95811235-acad5d00-0cc7-11eb-979d-c7165d8815b1.png)
(selecting row)
![image](https://user-images.githubusercontent.com/70230232/95811257-bafb7900-0cc7-11eb-8624-326878387e64.png)

2020-10-14 21:59 UTC, muddana-satish commented
Changed Opacity to 0.001 which is almost same as 0. Thanks @MatthewKhouzam for the suggestion.

2020-10-14 22:18 UTC, MatthewKhouzam approved these changes

2020-10-14 22:20 UTC, MatthewKhouzam requested changes
Please update the timeline-chart

2020-10-19 14:26 UTC, tahini requested changes
My main objection here is that we even need this patch. The day the default opacity is changed again in timeline-chart, it will have to be updated again... I'd expect the default value to come from the library and not have to specify it here, no? Like specify it only if/because the values from the library are not to our liking.

2020-10-19 17:52 UTC, muddana-satish commented
> My main objection here is that we even need this patch. The day the default opacity is changed again in timeline-chart, it will have to be updated again... I'd expect the default value to come from the library and not have to specify it here, no? Like specify it only if/because the values from the library are not to our liking.

I agree with the idea of setting all the default behaviors within the timeline-chart library. I believe this should be extended to other elements like states, labels, arrows, lines etc. Thank you for the suggestion.

The theia-ide/timeline-chart#57 is already merged and to set the default behaviors I have to make changes in timeline-chart repo. So is it okay if I open a new issue on that or do you want me to work as part of this issue?

2020-10-20 13:18 UTC, tahini commented
> I agree with the idea of setting all the default behaviors within the timeline-chart library. I believe this should be extended to other elements like states, labels, arrows, lines etc. Thank you for the suggestion.
> 
> The [theia-ide/timeline-chart#57](https://github.com/theia-ide/timeline-chart/pull/57) is already merged and to set the default behaviors I have to make changes in timeline-chart repo. So is it okay if I open a new issue on that or do you want me to work as part of this issue?

Does using the defaults from the timeline-chart involve changes to the timeline-chart repo, or just this one? What happens if you simply don't set the backgroundOpacity? Will it fallback to the timeline-chart's?

2020-10-20 15:52 UTC, muddana-satish commented
> > I agree with the idea of setting all the default behaviors within the timeline-chart library. I believe this should be extended to other elements like states, labels, arrows, lines etc. Thank you for the suggestion.
> > The [theia-ide/timeline-chart#57](https://github.com/theia-ide/timeline-chart/pull/57) is already merged and to set the default behaviors I have to make changes in timeline-chart repo. So is it okay if I open a new issue on that or do you want me to work as part of this issue?
> 
> Does using the defaults from the timeline-chart involve changes to the timeline-chart repo, or just this one? What happens if you simply don't set the backgroundOpacity? Will it fallback to the timeline-chart's?

With the current code base of timeline-chart, if we don't set any backgroundOpacity, then the library sets the default value to 1 which is incorrect because 'opacity: 1' would hide the lines inside the row. Attached screenshots of example app.

![image](https://user-images.githubusercontent.com/70230232/96611333-65b7fc80-12b1-11eb-871c-3bfbc9a24370.png)

We should handle the default behaviors correctly. So it would require some changes to timeline-chart.

2020-10-20 15:55 UTC, tahini commented
> We should handle the default behaviors correctly. So it would require some changes to timeline-chart.

Ok, I think the best would be to handle it in timeline-chart and then fix it here so we don't need the same hack. @MatthewKhouzam  any other opinion for this?

2020-10-22 20:04 UTC, MatthewKhouzam approved these changes

2020-10-22 20:06 UTC, MatthewKhouzam commented
I agree with @tahini  and @muddana-satish 

> We should handle the default behaviors correctly. So it would require some changes to timeline-chart.

but if we're going with the hack, then this is one I can live with. :+1:

2020-10-22 21:26 UTC, muddana-satish commented
Thanks for the feedback.

I will work on setting all the default behaviors within the timeline-chart library. Since I have to make sure that I don't set any default behavior explicitly in theia-trace-extension, I would need to make changes in this repo as well. Hence keeping this PR open.

2020-11-10 05:40 UTC, muddana-satish commented
No longer needed since https://github.com/theia-ide/timeline-chart/pull/70 is merged.

2020-11-10 05:40 UTC, closed without merging