Provide progress monitor for opening an experiment with cancel option
theia-ide/theia-trace-extension pull request #196
Opened 2020-12-03 19:37 UTC by bhufmann

In case a user selects a directory with large directory structure,
allow user to cancel the open procedure.

Fixes #195

Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>

2020-12-04 13:41 UTC, bhufmann commented
Picture below shows the dialog opened.

The text in the dialog is updated for the 3 steps during the opening process:

1. Open traces in an experiment: Finding traces
1. Open traces in an experiment: Opening traces
1. Open traces in an experiment: Creating experiment

![image](https://user-images.githubusercontent.com/413424/101170300-43353500-360c-11eb-9c82-2069dc85dbc1.png)

2020-12-10 17:03 UTC, bhufmann commented on viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
> +            text: 'Open traces in an experiment:'
remove experiment from user-facing string

2020-12-10 18:58 UTC, tahini requested changes
That's great improvement!

But I have an issue when cancelling an operation, it does not close the corresponding tab, so it is not possible to open it again after that.

Also, there are 2 parts here: 1- Monitor the cancellable operation and determine the message to show and 2- Display the message to the user.  While 2- belongs to the theia trace viewer, 1- should be in the base package. Maybe it's a bit tight for the MVP. If so could you add a TODO for later and open a corresponding issue to track this?

2020-12-10 19:17 UTC, bhufmann commented
> That's great improvement!
> 
> But I have an issue when cancelling an operation, it does not close the corresponding tab, so it is not possible to open it again after that.
> 
True. You need to close the tab first and the it will work again. I try to find a way to close the widget as well.

> Also, there are 2 parts here: 1- Monitor the cancellable operation and determine the message to show and 2- Display the message to the user. While 2- belongs to the theia trace viewer, 1- should be in the base package. Maybe it's a bit tight for the MVP. If so could you add a TODO for later and open a corresponding issue to track this?
I don't think I understand your comment. This PR is meant to monitor the progress on higher level. If you mean to add ways to cancel deeper in the execution stack (e.g. cancelling a REST command) then it's out of scope of this PR. Cancellation of REST commands as well as error handling needs to be tracked and handled outside PR.

2020-12-14 20:05 UTC, MatthewKhouzam approved these changes
Works here, you have my approval when Genevieve's comments are addressed.

2020-12-14 21:33 UTC, bhufmann commented
> Works here, you have my approval when Genevieve's comments are addressed.

I addressed the first comment in the source code. I replied also the second comment in https://github.com/theia-ide/theia-trace-extension/pull/196#issuecomment-742737213.

2020-12-15 01:37 UTC, MatthewKhouzam commented
That's what I understood, @tahini are your concerns addressed?

2020-12-15 02:30 UTC, tahini approved these changes
Yes, my comments were adressed, cancellation works well now! As for the other comment, when we also have a vscode extension, it will be clearer if we can/should move some code to base package.

2020-12-15 02:57 UTC, merged