Use the checkHealth method to check server status
theia-ide/theia-trace-extension pull request #224
Opened 2021-01-15 19:47 UTC by tahini

Closes #70

Instead of requested the experiments to see if the server is alive, use
the more light-weight checkHealth method.

Signed-off-by: Geneviève Bastien <gbastien@versatic.net>

2021-01-15 19:48 UTC, tahini commented
Requires tsp-typescript-client patch: https://github.com/theia-ide/tsp-typescript-client/pull/17
and trace server patch: https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/174907

2021-02-08 16:16 UTC, bhufmann requested changes
There has been conflicting code changes. Please rebase your patch. Thanks.

2021-02-19 14:03 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2021-02-25 18:48 UTC, MatthewKhouzam approved these changes
LGTM thanks!

2021-02-25 18:53 UTC, merged