Decouple trace explorer
theia-ide/theia-trace-extension pull request #295
Opened 2021-03-09 22:30 UTC by bhufmann

This pull requests consists of multiple commits to decouple the trace explorer widgets into pure React components. These new React components will be part of the packages/react-components and can be used in other web applications independently to Theia. 

- ` ReactAnalysisWidget` in `packages/react-components/patrace-explorer-analysis-widget.tsx`
- `ReactOpenTracesWidget` in `packages/react-components/trace-explorer-opened-traces-widget.tsx`

Along with this chain of commits, there are some code clean-ups and streamline the `SignalManager` and its usage.

2021-03-17 14:21 UTC, MatthewKhouzam approved these changes
Works well

2021-03-17 14:56 UTC, MatthewKhouzam approved these changes
Works in Electron, Firefox and gitpod. (Github swallowed my last "approved")

2021-03-17 14:58 UTC, MatthewKhouzam approved these changes
Works here. Is the `-impl` suffix standard?

2021-03-17 14:59 UTC, MatthewKhouzam approved these changes
I am OK with this, it works on my machine, I want to make sure we are not moving farther away from undo-redo though.

2021-03-17 19:51 UTC, bhufmann commented
> Works here. Is the `-impl` suffix standard?

I just want to distinguish the file of the interface from the file of the implementation, since the file name is not equal to the class name like in Java. Besides this suffix is used in other places in the code base, trace-server-url-provider-frontend-impl.ts. That's where I got the idea.

2021-03-25 18:34 UTC, PatrickTasse requested changes

2021-03-25 18:34 UTC, PatrickTasse commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
> +        signalManager().off(Signals.OPENED_TRACES_UPDATED, () => this.update());
The listener does not get removed because it is not the same instance being passed that was added earlier.

2021-03-25 18:34 UTC, PatrickTasse commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx
> +        signalManager().off(Signals.TRACEVIEWERTAB_ACTIVATED, (experiment: Experiment) => this.onOpenedTracesWidgetActivated(experiment));
The listener does not get removed because it is not the same instance being passed that was added earlier. (3x)

2021-03-25 18:34 UTC, PatrickTasse commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-views-widget.tsx
> +        signalManager().off(Signals.AVAILABLE_OUTPUTS_CHANGED, (payload: AvailableAnalysesChangedSignalPayload) => this.doHandleAvailableAnalysesChanged(payload));
The listener does not get removed because it is not the same instance being passed that was added earlier.

2021-03-25 18:34 UTC, PatrickTasse commented on theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
> +        signalManager().off(Signals.CLOSE_TRACEVIEWERTAB, (UUID: string) => this.onCloseExperiment(UUID));
The listener does not get removed because it is not the same instance being passed that was added earlier. (3x)

2021-03-25 19:12 UTC, PatrickTasse requested changes

2021-03-25 19:12 UTC, PatrickTasse commented on packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
> +        signalManager().off(Signals.TRACEVIEWERTAB_ACTIVATED, (experiment: Experiment) => this.onOpenedTracesWidgetActivated(experiment));
The listener does not get removed because it is not the same instance being passed that was added earlier. (3x)

2021-03-25 19:12 UTC, PatrickTasse commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
>          signalManager().off(Signals.OPENED_TRACES_UPDATED, () => this.update());
The listener does not get removed because it is not the same instance being passed that was added earlier.

2021-03-25 19:13 UTC, PatrickTasse requested changes

2021-03-25 19:13 UTC, PatrickTasse commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> +        signalManager().off(Signals.AVAILABLE_OUTPUTS_CHANGED, (payload: AvailableViewsChangedSignalPayload) => this.doHandleAvailableViewsChanged(payload));
The listener does not get removed because it is not the same instance being passed that was added earlier.

2021-03-25 19:15 UTC, PatrickTasse requested changes

2021-03-25 19:15 UTC, PatrickTasse commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> +        signalManager().off(Signals.EXPERIMENT_SELECTED, (experiment: Experiment | undefined) => this.onExperimentSelected(experiment));
The listener does not get removed because it is not the same instance being passed that was added earlier.

2021-03-26 21:22 UTC, PatrickTasse approved these changes

2021-03-26 21:24 UTC, PatrickTasse approved these changes

2021-03-26 21:25 UTC, PatrickTasse approved these changes

2021-03-26 21:25 UTC, PatrickTasse approved these changes

2021-03-29 13:47 UTC, merged