Analysis to view
theia-ide/theia-trace-extension pull request #297
Opened 2021-03-10 02:35 UTC by MatthewKhouzam

2021-03-10 15:43 UTC, bhufmann requested changes
Can you have 2 PRs, one for the change of vertical alignment and the second one for the renaming of the analysis to views? Both things are unrelated and should be tracked differently.

2021-03-10 15:43 UTC, bhufmann commented on .vscode/launch.json
> +                    "url": "webpack:///home/ematkho/work/git/theia-trace-extension/packages/react-components/src/components/table-output-component.tsx",
remove. Should not be needed

2021-03-16 18:31 UTC, bhufmann commented on packages/react-components/src/components/timegraph-output-component.tsx
> +                    }
the vertical align change is already merged, right?

2021-03-19 17:20 UTC, bhufmann requested changes

2021-03-19 17:29 UTC, MatthewKhouzam commented on packages/react-components/src/components/timegraph-output-component.tsx
> +                                console.log(currentStyle);
Fixed!

2021-03-19 19:20 UTC, bhufmann approved these changes
Thanks! Looks good to me.

2021-03-19 21:23 UTC, PatrickTasse requested changes
Should be abandoned? This is a console logging patch

2021-03-19 21:26 UTC, PatrickTasse commented on packages/react-components/src/components/timegraph-output-component.tsx
> +                            height = currentStyle['height'] * height;
Is this change intentional?

2021-03-22 14:52 UTC, bhufmann approved these changes
Thanks. Looks goo to me!

2021-03-22 15:03 UTC, PatrickTasse requested changes
Also need to update analysis/es -> views in:

trace-explorer-opened-traces-widget.tsx:299,301
trace-context-component:281

2021-03-22 15:03 UTC, PatrickTasse commented on README.md
> +Now, you will see 3 sections: **Opened Traces**, **Available Views** and **Time Graph Tooltip**. Select the trace that you opened and the available views will be populated. Now you can select differe
analysis -> views

2021-03-22 17:46 UTC, bhufmann approved these changes
Looks good to me!

2021-03-22 18:44 UTC, PatrickTasse approved these changes

2021-03-22 18:46 UTC, bhufmann approved these changes

2021-03-22 18:47 UTC, merged

2021-03-22 18:48 UTC, MatthewKhouzam commented
Thanks all!