Change trace-explorer-tooltip-widget title & Consolidate time graph tooltip information
theia-ide/theia-trace-extension pull request #320
Opened 2021-03-24 21:21 UTC by PatrickTasse

2021-03-24 22:12 UTC, muddana-satish commented
Looks good to me.

2021-03-25 13:46 UTC, bhufmann requested changes

2021-03-25 13:46 UTC, bhufmann commented on packages/react-components/src/components/timegraph-output-component.tsx
> +        const time = Math.round((elementRange.start + elementRange.end) / 2 + (offset ? offset : 0));
The formula is correct, but could (elementRange.start + elementRange.end) cause an overflow? Maybe the formular from below is safer (?):
Math.round((elementRange.start + ((elementRange.end - elementRange.start) / 2)) + (offset ? offset : 0))

2021-03-25 13:58 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2021-03-25 14:04 UTC, MatthewKhouzam approved these changes

2021-03-25 14:05 UTC, merged