Hide analysis that is not implemented on the client side
theia-ide/theia-trace-extension pull request #391
Opened 2021-06-11 19:46 UTC by IbrahimFradj

I have filtered out the view type that is not implemented in the client side (DATA_TREE). The expected result is that views of this type are not displayed in the available views 

 Fixes #296

**Before**

![image](https://user-images.githubusercontent.com/83769103/121736295-5f3af700-cac5-11eb-94bd-9f009d6a0371.png)

**After**

![image](https://user-images.githubusercontent.com/83769103/121741162-1dfa1580-cacc-11eb-9d3d-8b348e980405.png)

Signed-off-by: Ibrahim Fradj <ibrahim.fradj@ericsson.com>

2021-06-11 20:15 UTC, ebugden requested changes
Requested changes:
* **Change "Fixes #296" to something like "Contributes towards fixing #296"** - This is the client side of the work (still need server fixes) so we don't want to close the issue when this is merged. 

🌈 Thank you for this contribution! Non functional analyses were visibly frustrating for users during UX tests so this will have a significant positive impact.  

Question: How many views did this filter eliminate?

2021-06-16 14:46 UTC, MatthewKhouzam approved these changes
lgtm

2021-06-17 15:59 UTC, bhufmann approved these changes
Thanks. Totally makes sense.

2021-06-17 16:01 UTC, bhufmann commented
> Requested changes:
> 
>     * **Change "Fixes #296" to something like "Contributes towards fixing #296"** - This is the client side of the work (still need server fixes) so we don't want to close the issue when this is merged.
> 
> 
This has been done by Ibrahim and it's ready to be merged.

2021-06-17 16:23 UTC, ebugden approved these changes
Thanks for the update @IbrahimFradj! And thanks for the approval reminder @bhufmann!

2021-06-17 16:55 UTC, merged