Add contribution guidelines to readme
theia-ide/theia-trace-extension pull request #401
Opened 2021-06-23 17:46 UTC by ebugden

This could reduce repetition when onboarding new contributors. The linked step-by-step guide to contributing on GitHub (linked as [How to write and contribute changes](https://www.dataschool.io/how-to-contribute-on-github/)) is _excellent_.

2021-06-25 13:59 UTC, IbrahimFradj commented
- For the guidelines, I think the readme is good. 

- For the validation message, I think it is a good standard, not too high, not too low, this validation message helps a lot the reviewer and can help other people to understand the PR and help them in their problem.

it looks good to me. Thank you a lot.

2021-06-25 14:03 UTC, IbrahimFradj approved these changes

2021-06-25 17:47 UTC, MatthewKhouzam submitted a review, later dismissed
Looks good, we need a signoff though!

2021-07-07 00:27 UTC, MatthewKhouzam commented
> Looks good, we need a signoff though!

@ebugden  I mean you need to add a `signed-off-by: ` at the end of your commit message, or else DCO will fail. This is our IP protection bot to make sure people contributing don't steal code. By adding the signed off, you're saying you wrote the code originally.

2021-07-13 21:28 UTC, ebugden commented
> Looks good, we need a signoff though!

Added!

2021-07-15 22:14 UTC, IbrahimFradj approved these changes

2021-07-23 13:36 UTC, MatthewKhouzam submitted a review, later dismissed

2021-07-26 17:11 UTC, bhufmann requested changes
@ebugden could you please add a line that a signed-off <email-address> is required at the end of the commit message? Otherwise it looks good to me.
Thanks!

2021-07-26 18:06 UTC, ebugden commented
> @ebugden could you please add a line that a signed-off is required at the end of the commit message? Otherwise it looks good to me.
> Thanks!

Commit message has a signoff. Should the PR description also have one?

![image](https://user-images.githubusercontent.com/28311615/127037202-447f1fc3-4642-4f79-97ee-bcacfc3f71fd.png)

2021-07-27 14:46 UTC, bhufmann commented
> > @ebugden could you please add a line that a signed-off is required at the end of the commit message?
> 
> Commit message has a signoff. Should the PR description also have one?
> 
There is a misunderstanding. Your PR has a signed-off and it's fine. What I meant was that the contribution guide should state that a signed-off is required.

2021-08-03 21:37 UTC, ebugden commented
Requested changes:
- [x] Add including signoff in contribution guidelines

Updated! [See updated version](https://github.com/ebugden/theia-trace-extension/tree/contribution-guidelines#how-to-contribute-code)

2021-08-05 19:28 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2021-08-05 20:12 UTC, merged