Add the shift-click selection interval in XY chart
theia-ide/theia-trace-extension pull request #498
Opened 2021-09-22 21:34 UTC by IbrahimFradj

We can select interval with shift-click.

Fixes #439.

Signed-off-by: Ibrahim Fradj <ibrahim.fradj@ericsson.com>

2021-09-23 13:41 UTC, ebugden commented
Is this a feature in Trace Compass that current TC users expect to have and enjoy? 

If not, could you explain:
* An example where it's much more convenient to adjust an existing selected area instead of re-selecting the adjusted smaller/larger area?
* Why implementing adjusting an existing area with shift-click is the most practical/intuitive? (ex. Instead of being able to click on the bars showing the start/end of the selected area to drag them smaller/larger)

2021-09-24 00:51 UTC, IbrahimFradj commented
> 
> 
> I definitely should have asked the following questions before assigning the associated issue to "High priority". I apologize for not asking these earlier!
> 
> Is this a feature in Trace Compass that current TC users expect to have and enjoy?
> 
> If not, could you explain:
> 
>     * An example where it's much more convenient to adjust an existing selected area instead of re-selecting the adjusted smaller/larger area?
> 
>     * Why implementing adjusting an existing area with shift-click is the most practical/intuitive? (ex. Instead of being able to click on the bars showing the start/end of the selected area to drag them smaller/larger)
> 
> 
> Thanks for working on the XY chart navigation! ☀️

In fact, this functionality exists in Trace compass and in timeline chart on theia-trace-extension. my goal is that xy chart has the same functionality as timeline chart.
This can be useful when for example I find a place where I want to make a selection without changing the beginning of the selection

2021-09-24 13:34 UTC, bhufmann commented
> I definitely should have asked the following questions before assigning the associated issue to "High priority". I apologize for not asking these earlier!
> 
> Is this a feature in Trace Compass that current TC users expect to have and enjoy?
> 
> If not, could you explain:
> 
>     * An example where it's much more convenient to adjust an existing selected area instead of re-selecting the adjusted smaller/larger area?
> 
>     * Why implementing adjusting an existing area with shift-click is the most practical/intuitive? (ex. Instead of being able to click on the bars showing the start/end of the selected area to drag them smaller/larger)
> 
> 
> Thanks for working on the XY chart navigation! sunny

The advantage of this capability is that users can keep one side of selection (start or end) constant and then extend the selection without changing the starting point to measure time from a given timestamp on.

2021-09-28 16:09 UTC, ebugden commented
@IbrahimFradj Can you rebase on master so that you get the recent Gitpod fixes? I'd like to play around with this feature to see if there's a quick way we could make it discoverable (ex. changing the cursor to a ⟷ when they press shift while hovering on a graph).

Thank you for the extra context IbrahimFradj and bhufmann. I don't know the practical analysis applications of measuring times with a fixed reference, but I trust your experience.

2021-09-29 14:24 UTC, IbrahimFradj commented
> 
> 
> @IbrahimFradj Can you rebase on master so that you get the recent Gitpod fixes? I'd like to play around with this feature to see if there's a quick way we could make it discoverable (ex. changing the cursor to a ⟷ when they press shif

2021-09-29 14:54 UTC, IbrahimFradj commented
> 
> 
> @IbrahimFradj Can you rebase on master so that you get the recent Gitpod fixes? I'd like to play around with this feature to see if there's a quick way we could make it discoverable (ex. changing the cursor to a ⟷ when they press shift while hovering on a graph).
> 
> Thank you for the extra context **IbrahimFradj** and **bhufmann**. I don't know the practical analysis applications of measuring times with a fixed reference, but I trust your experience.

@ebugden  I rebased on master, gitpod works.

2021-09-29 18:24 UTC, PatrickTasse commented
> Why implementing adjusting an existing area with shift-click is the most practical/intuitive? (ex. Instead of being able to click on the bars showing the start/end of the selected area to drag them smaller/larger)

This could make it impossible to replace a narrow range selection with a new single selection in one click (without needing to click somewhere far away first).

Shift to extend selection also applies when using keyboard left/right navigation. That is really useful to make a selection to the exact time bounds of a state or group of states.

2021-09-29 18:40 UTC, PatrickTasse requested changes

2021-09-29 18:40 UTC, PatrickTasse commented on packages/react-components/src/components/xy-output-component.tsx
> +                end: this.getTimeX(event.offsetX)
If you drag selection outside of the bounds of the XY chart then you start receiving event.offsetX in another component's coordinates and the end time is wrong.

2021-09-29 21:06 UTC, PatrickTasse approved these changes

2021-09-30 18:38 UTC, ebugden commented
> I rebased on master, gitpod works.

Looks good to me! Thanks for the update. Consistent navigation features across chart types is important to avoid user confusion.

2021-10-01 15:53 UTC, bhufmann approved these changes
LGTM. Thanks!

2021-10-01 15:56 UTC, merged