Selected view highlighted immediately after clicked + view selection cleared after trace switched
theia-ide/theia-trace-extension pull request #549
Opened 2021-11-01 16:01 UTC by ywang001

fixes #540

1) Whenever you click on one of the available views, it is highlighted immediately even if you do not resize the sidebar.
2) Whenever you switch to another opened trace, the view selection will be cleared. For example, you have wget-second-call opened and CPU Usage selected and highlighted. If you switch from wget-second-call to wget-first-call, none of the available views will be selected or highlighted.

Signed-off-by: yining wang <yining.wang@ericsson.com

2021-11-01 17:52 UTC, bhufmann submitted a review, later dismissed
Looks good to me. Thanks for the contribution.

2021-11-03 13:52 UTC, IbrahimFradj requested changes
LGTM, i think you have just to squash the 2 commit into 1. Thank you for your contribution.

2021-11-03 16:24 UTC, mirsky-work commented
> LGTM, i think you have just to squash the 2 commit into 1. Thank you for your contribution.

The 2 commits seem unrelated, so IMO should remain separated. But @ywang001, please format the commit messages: short title in imperative form, starts with a capital letter

2021-11-03 22:00 UTC, PatrickTasse requested changes

2021-11-03 22:00 UTC, PatrickTasse commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> +            title={outputName + ': ' + outputDescription}
What is the effect of this line?

2021-11-03 22:00 UTC, PatrickTasse commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
>              style={props.style}
Is there supposed to be a tooltip when hovering over a text with the ellipsis? I don't see any.

2021-11-03 22:00 UTC, PatrickTasse commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> -            title={outputName + ': ' + outputDescription}
If this was added by mistake in previous commit, that commit should be amended to remove it.

2021-11-03 22:00 UTC, PatrickTasse commented on packages/react-components/style/trace-explorer.css
> -    text-overflow: ellipsis;
These changes seem related and necessary to the first commit, but the first commit is unrelated to this PR.

If you intended to make these changes in a separate PR, the first commit and this commit should simply be removed from this PR.

2021-11-05 17:34 UTC, PatrickTasse approved these changes

2021-11-05 17:42 UTC, bhufmann approved these changes
LGTM. Thanks for the contribution!

2021-11-05 17:56 UTC, merged