Add min height limit for output view
theia-ide/theia-trace-extension pull request #553
Opened 2021-11-02 19:22 UTC by hriday-panchasara

fixes #537

avoids title-bar texts being mixed and makes diagrams more readable

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

![Screen Shot 2021-11-02 at 1 47 05 PM](https://user-images.githubusercontent.com/92893187/139931609-c1b0c799-4bbb-4be4-b11d-0dff791ade7a.png)

2021-11-03 15:00 UTC, IbrahimFradj approved these changes
LGTM, thank you. Maybe just a small remark in your commit i think we do it:

1.  Title 
2.  Description
3.  Fixes 
4.  signed-off

2021-11-05 18:20 UTC, bhufmann commented
While I agree that the issue of overflowing of the title needs to be fixed, I think having a minimum size will remove the possibility to have a graph with smaller height. For example, it's interesting to have a small CPU usage line chart on top of other views. 

![image](https://user-images.githubusercontent.com/413424/140559269-1b3296ed-4963-4aef-90e9-1e4d659facf4.png)

What do think about the alternative to add eclipse (e.g. "CPU U...") to the title and don't overflow the title box and also have tooltip that will pop-up with full title name if the user hovers over the title? With this, you can make the minimum height much smaller. Please let me know.

2021-11-05 21:42 UTC, hriday-panchasara commented
Removed output view minimum height bound, and implemented ellipsis and tooltip to deal with title bar text overflow:

![Screen Shot 2021-11-05 at 4 35 35 PM](https://user-images.githubusercontent.com/92893187/140581817-4afe1dea-6814-4a30-91f6-989b2c9ccf3c.png)

2021-11-10 16:08 UTC, bhufmann approved these changes
Thanks. Looks good to me.

2021-11-10 17:57 UTC, mirsky-work commented
> Removed output view minimum height bound, and implemented ellipsis and tooltip to deal with title bar text overflow:

Looks good. Don't forget to update the PR title and description and also clean the commits history.

2021-11-10 19:21 UTC, hriday-panchasara commented
> > Removed output view minimum height bound, and implemented ellipsis and tooltip to deal with title bar text overflow:
> 
> Looks good. Don't forget to update the PR title and description and also clean the commits history.

Updated the PR title and amended the commit message. Let me know if any other changes are needed.

2021-11-10 22:22 UTC, IbrahimFradj commented
> Updated the PR title and amended the commit message. Let me know if any other changes are needed.

I think the changes should also be in the commit message. 
Slogan to shorten to <= 50 characters.

2021-11-12 15:38 UTC, bhufmann requested changes
End result looks good, but could you squash both commits? The one where you limit the height is not needed. Also, make sure that the commit message is formatted (as Ibrahim suggested)

2021-11-15 16:28 UTC, hriday-panchasara commented
> End result looks good, but could you squash both commits? The one where you limit the height is not needed. Also, make sure that the commit message is formatted (as Ibrahim suggested)

Hey Bernd, I've squashed the commits and formatted the commit message as requested.

2021-11-15 18:44 UTC, bhufmann approved these changes
Looks good to me. Thanks for the update!

2021-11-15 19:34 UTC, merged