Rename opened traces context menu delete command
theia-ide/theia-trace-extension pull request #582
Opened 2021-11-30 18:39 UTC by hriday-panchasara

fixes #277

'Delete trace' renamed to 'Remove trace' to make it consistent with the remove traces tooltip

![Screen Shot 2021-11-30 at 12 38 34 PM](https://user-images.githubusercontent.com/92893187/144107652-0bb9f946-2ff1-4abe-8d7b-124dc1c738ab.png)

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

2021-11-30 20:33 UTC, bhufmann requested changes
Thanks for the contribution.

The tooltip of the delete button says "Remove Traces ...". I think the tooltip should say "Remove Trace ..." instead. Could you please also update that in this PR? I think it fits well in its scope.

2021-11-30 20:33 UTC, bhufmann commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-commands.ts
>      export const DELETE_TRACE: Command = {
DELETE_TRACE should be changed too

2021-11-30 20:33 UTC, bhufmann commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-commands.ts
>          id: 'trace-explorer:delete-trace',
delete-trace too

2021-12-02 16:03 UTC, bhufmann approved these changes
Thanks a lot. Looks good to me.

2021-12-02 20:16 UTC, PatrickTasse approved these changes

2021-12-02 20:17 UTC, merged