Readme: Add architecture diagram
theia-ide/theia-trace-extension pull request #587
Opened 2021-12-03 16:39 UTC by ebugden

Signed-off-by: Erica Bugden <erica.bugden@gmail.com>

2021-12-03 16:40 UTC, ebugden commented
Should this "Architecture" section go above or below the "Related code" section?

2021-12-21 18:32 UTC, bhufmann requested changes
Looks good to me. Please update the link to the image and rebase to the latest master.

2021-12-21 18:32 UTC, bhufmann commented on README.md
> +![Trace viewer architecture diagram](https://raw.githubusercontent.com/ebugden/theia-trace-extension/architecture-diagram/doc/images/theia-trace-viewer-architecture.PNG)
Make sure it points to the one in `theia-ide`.

2022-01-18 16:21 UTC, bhufmann approved these changes

2022-01-18 22:00 UTC, bhufmann commented
@ebugden could you please rebase this PR to latest master?

2022-01-19 18:21 UTC, PatrickTasse submitted a review, later dismissed

2022-01-19 19:12 UTC, bhufmann requested changes
Please update this PR with right link to the file. I did a rebase on GitHub, but  if you could just update the PR and make sure that it's rebased on master, then you can remove my merge commit. I prefer actually not to have the merge commit.

2022-01-19 19:12 UTC, bhufmann commented on README.md
> +![Trace viewer architecture diagram](https://raw.githubusercontent.com/ebugden/theia-trace-extension/architecture-diagram/doc/images/theia-trace-viewer-architecture.PNG)
@ebugden this needs to be still updated to point to the file in this repo.

2022-01-19 22:33 UTC, ebugden commented
Update:
* Change image path to pull from main repo
* Rebase on master

2022-01-20 15:42 UTC, bhufmann approved these changes
Thanks for the updates. LGTM.

2022-01-20 15:55 UTC, PatrickTasse approved these changes

2022-01-20 15:59 UTC, merged