Update @theia/cli dependency to version 1.21.0
theia-ide/theia-trace-extension pull request #616
Opened 2022-01-07 21:19 UTC by Rodrigoplp-work

| Package | Current | Updated to |
| --- | --- | --- |
| @theia/cli | 1.10.0 | 1.21.0 |

The update resolves Dependabot alerts for the following packages:

- color-string;
- glob-parent;
- underscore;
- is-svg;
- yargs-parser;
- serialize-javascript.

Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>

2022-01-11 21:14 UTC, bhufmann requested changes

2022-01-12 21:05 UTC, Rodrigoplp-work commented on package.json
> +    "@theia/cli": "^1.21.0",
Used a fixed version for `theia/cli`.

Changed the typescript dependency from "latest" to "4.5.4", which fixes the tsc error.

I couldn't find why this happens, but using "latest" installs 4.5.2, which throws the `tsc: not found` error. Removing typescript and installing it again adds the 4.5.4 version, and that one allows the build to pass.

2022-01-12 21:25 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2022-01-12 21:45 UTC, PatrickTasse approved these changes

2022-01-12 22:34 UTC, merged