Fix invalid path on Windows when opening traces
theia-ide/theia-trace-extension pull request #674
Opened 2022-02-08 20:59 UTC by hoangphamEclipse

Currently, on Windows, Theia returns a path that starts with "/" (e.g. "/c:/").  This is an invalid path. This commit resolves this issue by using FileUri to convert the original file path returned by Theia to a platform specific path.

2022-02-08 21:17 UTC, bhufmann requested changes
Your commit message needs to be formatted properly and you need to add a correctly formatted signed-off-by line

2022-02-08 21:17 UTC, bhufmann commented on theia-extensions/viewer-prototype/src/node/backend-file-service-impl.ts
> +        /*
remove trailing whitespaces

2022-02-08 22:06 UTC, Rodrigoplp-work approved these changes

2022-02-09 13:28 UTC, bhufmann requested changes
The commit message is not formatted properly has to long lines. The main readme has a section about how to contribute code and format the message.
https://github.com/theia-ide/theia-trace-extension#how-to-contribute-code

Please update the commit message accordingly.

2022-02-09 19:52 UTC, bhufmann approved these changes
Thanks for fixing this. Looks good to me.

2022-02-09 20:20 UTC, Rodrigoplp-work approved these changes

2022-02-09 21:49 UTC, merged

2022-02-09 21:50 UTC, bhufmann commented
Fixes #545