Split X-axis views and non X-axis views
theia-ide/theia-trace-extension pull request #675
Opened 2022-02-09 16:17 UTC by hriday-panchasara

Implement different visual containers for views that have an X axis and those that don't

fixes #287

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

2022-02-11 21:39 UTC, PatrickTasse commented
At first glance it does not behave how I would have expected, but we should consider its pros and cons.

The cons I see with two containers is that it creates two scrollable areas, so once they are created a user cannot see two initial-sized graphs at the same time just by scrolling, the sash needs to be resized. When there are a lot of outputs open, to find a specific one that is hidden, the user has to know to scroll the right area. Also the horizontal scroll bar moves around as outputs are created and removed, and could be hard to find.

What I expected was simply that the order of outputs would be restricted so that timescale outputs are on top and non-timescale outputs on the bottom. But the con of that is that the horizontal scroll bar is at the bottom of the tab where it could be far from the timescale outputs. It is like that in the original implementation, but I am not sure if it was a goal to change that.

A useful new feature is that it is now possible to fix an output while the other outputs can be scrolled. But in this implementation, the outputs that can be scrolled are limited to the outputs of the 'other' (timescale/non-timescale) category. You can't fix a graph while you scroll through other graphs, which would be a nice improvement.

An idea I had to achieve that was to add a pin feature to the output components. This could be a new button added to the output handle. "Pin to Top" for timescale outputs, "Pin to Bottom" for non-timescale outputs. The pinned outputs would then be moved out of the scrollable area, but they would keep their resize handle. Then all the non-pinned outputs would remain part of a scrollable area, as today.

2022-02-14 21:38 UTC, Rodrigoplp-work commented
Thank you for calling a meeting about this, Hriday. My perspective from that discussion is to have, if possible:

- Charts and tables get added like we currently have on the master branch, but time-line charts are automatically moved to be on the top, tables at the bottom;
- The horizontal bar that indicates zoom appears below the last time-line chart, above the first table;
- Time-line charts and tables can be moved up and down but, after the user ends dragging, the tables move to be below the time-line charts.

Even better if this could be achieved without adding the react-split library.

I like this solution because it would reduce the amount of scroll bars on screen, remove the white blank spaces created by the "split" solution, and eliminate the problem of hidden charts in the middle of the screen.

2022-02-22 23:05 UTC, Rodrigoplp-work commented
Amazing! Just like we discussed. Thank you Hriday.

2022-02-22 23:05 UTC, Rodrigoplp-work submitted a review, later dismissed

2022-02-22 23:14 UTC, PatrickTasse requested changes
I think the timeNavigator should always be visible. So if there are more time scale outputs than fits in the window height, the timeNavigator should float and snap to the bottom of the window.

2022-02-23 20:07 UTC, hriday-panchasara commented
> I think the timeNavigator should always be visible. So if there are more time scale outputs than fits in the window height, the timeNavigator should float and snap to the bottom of the window.

@PatrickTasse I tired but I was unable to stick the timeNavigator on overflow.

To make the timeNavigator 'fixed' when its scrolled out of view, we can attach the following class to the component:
![Screen Shot 2022-02-23 at 13 52 17 PM](https://user-images.githubusercontent.com/92893187/155397792-177c5556-7bc0-4d57-a748-f12405272a9c.png)

But this would only work when the parent component does not have an overflow value. So removing 'overflow-y: scroll' from the RGL container would work but it would mean that our view is not scrollable anymore. Also, to make 'position' property work for RGL children we have to add the following prop to the RGL container: 'useCSSTransforms: false'. But by doing so the charts become static and I'm unable to interact with them. Looking into this css issue the recommended fix I found was to put the 'sticky' element in a separate container. By doing so the TimeNavigator won't be a part of the resizable Grid, hence we wouldn't have a visible divider between the two types of charts:
![Screen Shot 2022-02-23 at 14 02 33 PM](https://user-images.githubusercontent.com/92893187/155399330-0f4010a9-c47b-4d5f-b9cd-433aacbc49fe.png)

2022-02-25 15:19 UTC, hriday-panchasara commented
@PatrickTasse @Rodrigoplp-work updated the PR to do all of the above as well as keep the timeNavigator visible on overflow:
![Screen Shot 2022-02-25 at 09 19 26 AM](https://user-images.githubusercontent.com/92893187/155740439-1c56a75b-a361-4fa1-bccf-72660da50eae.png)

2022-02-25 20:12 UTC, PatrickTasse approved these changes

2022-03-03 15:04 UTC, merged