Update open trace icon to avoid confusion
theia-ide/theia-trace-extension pull request #681
Opened 2022-02-14 20:55 UTC by hoangphamEclipse

Currently, the trace extension uses the 'Open folder' icon for the open
trace button. This can be confusing for users, since they can see the action
as closing the current trace and opening a new one. The expected understanding
of this action is opening a new trace along side the old ones. This commit
updates the icon of the open trace button to 'Folder plus' to avoid this
confusion.

Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>

2022-02-14 21:54 UTC, bhufmann commented
Note, that #679 is needed so that the button is visible.

2022-02-14 22:05 UTC, bhufmann commented
> Note, that #679 is needed so that the button is visible.

#679 is merged.

2022-02-15 14:39 UTC, bhufmann submitted a review, later dismissed

2022-02-15 15:32 UTC, bhufmann requested changes
currently font-awesome 4.7.0 is used and it doesn't have that icon. 4.7.0 is used because theia-core is using this version.

2022-02-16 17:49 UTC, hriday-panchasara commented
One way to supply a custom icon to OPEN_TRACE:
![Screen Shot 2022-02-16 at 11 48 27 AM](https://user-images.githubusercontent.com/92893187/154325234-4749b22d-7e87-41b1-9253-c39178b37f49.png)
![Screen Shot 2022-02-16 at 11 48 35 AM](https://user-images.githubusercontent.com/92893187/154325252-28aa6ed8-e841-45af-8daa-18a439ef8a68.png)

2022-02-16 21:51 UTC, Rodrigoplp-work commented
> One way to supply a custom icon to OPEN_TRACE: ![Screen Shot 2022-02-16 at 11 48 27 AM](https://user-images.githubusercontent.com/92893187/154325234-4749b22d-7e87-41b1-9253-c39178b37f49.png) ![Screen Shot 2022-02-16 at 11 48 35 AM](https://user-images.githubusercontent.com/92893187/154325252-28aa6ed8-e841-45af-8daa-18a439ef8a68.png)

Thank you Hriday! Great suggestion.

But when I tried it, the icon still wouldn't show up. I had to use `background` instead of `mask`, like this:

First create a file called `packages/rect-components/style/folder-plus-solid.svg` with this content:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M464 96h-192l-64-64h-160C21.5 32 0 53.5 0 80v352C0 458.5 21.5 480 48 480h416c26.5 0 48-21.5 48-48v-288C512 117.5 490.5 96 464 96zM336 311.1h-56v56C279.1 381.3 269.3 392 256 392c-13.27 0-23.1-10.74-23.1-23.1V311.1H175.1C162.7 311.1 152 301.3 152 288c0-13.26 10.74-23.1 23.1-23.1h56V207.1C232 194.7 242.7 184 256 184s23.1 10.74 23.1 23.1V264h56C349.3 264 360 274.7 360 288S349.3 311.1 336 311.1z"/></svg>
```

Then add this to the end of `packages/rect-components/style/output-components-style.css`:

```
.open-trace-icon {
  background: url('folder-plus-solid.svg') no-repeat center;
}
```

Let me know if that works.

2022-02-17 18:01 UTC, bhufmann commented
> ```
> https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc.
> ```

I don't think we can use the font, because it's under commercial license.  We need to find an other icon source.

2022-03-15 17:50 UTC, hoangphamEclipse commented
Since Theia does not supported font-awesome 5, which provides the icon that we needed, we opted for @vscode/codicons instead. The icon used is found [here](https://github.com/microsoft/vscode-codicons/blob/main/src/icons/new-folder.svg).

2022-03-15 20:30 UTC, Rodrigoplp-work approved these changes

2022-03-16 15:41 UTC, merged